In [1]:
from sklearn.datasets import fetch_mldata
mnist = fetch_mldata('MNIST original')

In [2]:
from sklearn.model_selection import train_test_split
train_img, test_img, train_lbl, test_lbl = train_test_split(mnist.data, mnist.target, test_size=1/7.0, random_state=0)

In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [4]:
# Fit on training set only
scaler.fit(train_img)

C:\Users\odilon\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
# Apply transform to both training set and the test set
train_img = scaler.transform(train_img)
test_img = scaler.transform(test_img)

C:\Users\odilon\Anaconda3\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype uint8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [6]:
from sklearn.decomposition import PCA

In [7]:
# Make an instance of the Model
pca = PCA(.95)

In [8]:
pca.fit(train_img)

PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [9]:
# Number of components
pca.n_components_

330

In [10]:
train_img = pca.transform(train_img)
test_img = pca.transform(test_img)

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
logisticRegression = LogisticRegression(solver='lbfgs')

In [14]:
logisticRegression.fit(X=train_img, y=train_lbl)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='lbfgs', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
# Prediction for One Observation (image)
logisticRegression.predict(test_img[0].reshape(1, -1))

array([ 1.])

In [27]:
logisticRegression.predict(test_img[0:100])

array([ 1.,  9.,  2.,  2.,  7.,  1.,  8.,  3.,  3.,  7.,  7.,  6.,  0.,
        1.,  2.,  9.,  8.,  7.,  7.,  9.,  3.,  8.,  5.,  8.,  1.,  2.,
        3.,  7.,  5.,  5.,  6.,  0.,  9.,  0.,  2.,  5.,  0.,  0.,  2.,
        9.,  5.,  7.,  2.,  4.,  8.,  6.,  0.,  8.,  3.,  9.,  9.,  4.,
        3.,  9.,  8.,  8.,  6.,  0.,  3.,  1.,  9.,  6.,  4.,  0.,  2.,
        9.,  7.,  0.,  9.,  3.,  8.,  6.,  3.,  1.,  2.,  2.,  2.,  2.,
        5.,  8.,  1.,  8.,  2.,  7.,  4.,  6.,  3.,  1.,  0.,  9.,  2.,
        7.,  4.,  8.,  7.,  1.,  6.,  7.,  8.,  3.])

In [28]:
test_lbl[0:100]

array([ 1.,  9.,  2.,  2.,  7.,  1.,  8.,  3.,  3.,  7.,  7.,  5.,  0.,
        1.,  2.,  9.,  2.,  7.,  7.,  9.,  9.,  8.,  5.,  8.,  1.,  2.,
        3.,  7.,  5.,  5.,  6.,  0.,  9.,  0.,  2.,  5.,  0.,  0.,  2.,
        9.,  5.,  7.,  2.,  4.,  8.,  6.,  0.,  8.,  3.,  9.,  9.,  4.,
        3.,  9.,  8.,  1.,  6.,  0.,  3.,  1.,  9.,  6.,  4.,  0.,  2.,
        9.,  3.,  0.,  9.,  3.,  8.,  6.,  3.,  1.,  2.,  2.,  3.,  2.,
        5.,  1.,  1.,  8.,  3.,  7.,  4.,  6.,  3.,  1.,  0.,  9.,  2.,
        7.,  4.,  8.,  7.,  1.,  6.,  7.,  8.,  3.])

In [29]:
logisticRegression.score(test_img, test_lbl)

0.92000000000000004